# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QBoxLayout, QFileDialog, QHBoxLayout, QStatusBar, QWidget, QPushButton, QVBoxLayout
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor, QFont, QPalette
from PyQt5.QtWidgets import QApplication, QPushButton
import controller 
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(123, 354, 171, 101))
        self.button1.setObjectName("button1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(131, 244, 121, 61))
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "press me"))
        self.label1.setText(_translate("MainWindow", "hello"))
def files():
        fileName, _ = QFileDialog.getOpenFileName(window, "Selecciona los mediose",
                ".", "Video Files (*.mp4 *.flv *.ts *.mts *.avi)")

        if fileName != '':
            controller.video(fileName)
            statusBar.showMessage(fileName)

if __name__ == "__main__":
    import sys
    app = QApplication([])
    app.setStyle('Fusion')
    palette = QPalette()
    # dark_palette = QPalette()
    # dark_palette.setColor(QPalette.Window, QColor(53, 53, 53))
    # app.setPalette(dark_palette)
    window = QWidget()
    window.setWindowTitle("Player")
    window.setGeometry(109,100,2000,1500)
    window.setFixedSize(2000, 1500)
    openButton = QPushButton("Open Video",window)
    openButton.setGeometry(0,1390,2000,90)
    openButton.setFont(QFont("Noto Sans", 8))
    openButton.setFixedHeight(50)
    openButton.clicked.connect(files)
    statusBar = QStatusBar(window)
    statusBar.setFont(QFont("Noto Sans", 7))
    statusBar.showMessage("Ready")
    statusBar.setGeometry(940,1440,2000,50)
    statusBar.setFixedHeight(50)
    # controlLayout = QHBoxLayout()
    # controlLayout.setContentsMargins(0, 0, 0, 0)
    # controlLayout.addWidget(openButton)
    # layout = QVBoxLayout()
    # layout.addLayout(controlLayout)
    # layout.addWidget(statusBar)
    

    # layout = QVBoxLayout()
    # layout.addWidget(QPushButton('Top'))
    # layout.addWidget(QPushButton('Bottom'))
    # window.setLayout(layout)
    window.show()
    sys.exit(app.exec_())
